spring:
  config:
    activate:
      on-profile: local
  application:
    name: AIShortsStudio
  datasource:
    url: jdbc:postgresql://localhost:5432/AiShortsStudio
    username: "postgres"
    password: "1234"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false