spring:
  config:
    activate:
      on-profile: prod
  application:
    name: AIShortsStudio
  datasource:
    url: jdbc:postgresql://localhost:5432/AiShortsStudio
    username: "postgres"
    password: "1234"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082